# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200241f58aa0b216f77f4c30baa7658e22c6b61c75125e92dfec554be65ddd02ac7c20f47205eecdfe422b839c54dcf7a800f189ef25e79e9a5dc408395e6191

test:
  secret_key_base: 3c561e3caceeafddd8b4393c51e0b99a51e1695f09f171a6ef45d410890e077bca1f17c5dd6147b94281891f9391494c6c521c45d635f98020b5bf6d89c8c41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
